spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Cards Microservice QA Development"
  contact-details:
    name: "John Doe"
    email: "johndoe@go.com"
  onCallSupport:
    - "555-01234"
    - "555-56789"