services:
  accounts:
    image: "accounts:1.0.0"
    container_name: "accounts_ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
            cpus: "1"
            memory: 700M
    networks:
        - backend
  loans:
    image: "loans:1.0.0"
    container_name: "loans_ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 700M
    networks:
      - backend
  cards:
    image: "cards:1.0.0-SNAPSHOT"
    container_name: "cards_ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 700M
    networks:
      - backend

networks:
    backend:
        driver: bridge