build:
  version: "0.0.3"

accounts:
    message: "Accounts Microservice Local Development"
    contact-details:
      name: "John Doe"
      email: "johndoe@go.com"
    onCallSupport:
      - "555-01234"
      - "555-56789"


