build:
  version: "1.0"

loans:
  message: "Loans Microservice Local Development"
  contact-details:
    name: "John Doe"
    email: "johndoe@go.com"
  onCallSupport:
    - "555-01234"
    - "555-56789"
