server:
  port: 8080

spring:
  application:
    name: accounts

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import:
      - classpath:application_qa.yml
      - classpath:application_prod.yml
  profiles:
    active: "prod"

build:
  version: "0.0.3"

accounts:
    message: "Accounts Microservice Local Development"
    contact-details:
      name: "John Doe"
      email: "johndoe@go.com"
    onCallSupport:
      - "555-01234"
      - "555-56789"


