spring:
  application:
    name: "configserver"

  profiles:
    active: git
  #    active: native


  cloud:
    config:
      server:
        git:
          uri: "git@github.com:navalkishoreb/microservice-with-spring-boot-config-server.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  #        native:
  #          search-locations: "classpath:/config"
  #          search-locations: file:///Users/nkishorebarthwal/Documents/Learning/udemy_course/config

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true


encrypt:
  key: "mysecretkey"
