version: '3.8'

services:
  accountsdb:
    container_name: "accountsdb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "accountsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: "loansdb"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "loansdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: "cardsdb"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "cardsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config


  configserver:
    image: "navalkishoreb/configserver:2.0.1"
    container_name: "configserver_ms"
    ports:
      - "8071:8071"
    volumes:
      - /Users/nkishorebarthwal/.ssh/id_naval_github:/root/.ssh/id_rsa:ro
      - /Users/nkishorebarthwal/.ssh/id_naval_github.pub:/root/.ssh/id_rsa.pub:ro
      - /Users/nkishorebarthwal/.ssh/known_hosts:/root/.ssh/known_hosts
    environment:
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "git@github.com:navalkishoreb/microservice-with-spring-boot-config-server.git"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      #      test: "curl --fail --silent localhost:8071/accounts/default || exit 1"
      retries: 10
      interval: 10s
      timeout: 5s
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "navalkishoreb/accounts:2.0.1"
    container_name: "accounts_ms"
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "navalkishoreb/loans:2.0.1"
    container_name: "loans_ms"
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "navalkishoreb/cards:2.0.1"
    container_name: "cards_ms"
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  backend:
    driver: "bridge"